db:
  type: mssql
  mssql:
    username: sa
    password: 
    host: 192.168.1.11
    port: 1433
    database: jssljs

output:
  csharp:
    dto: ./../../output
    data:
    bussiness:
    controller: